name: 'Automatic release'
on: 
  push:
    tags:
      - '*'
jobs:
  assembly:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Assemble
        run: |
          zip -r9 cambridge-modpack.zip res tetris
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: cambridge-modpack.zip